const countries = [
    'Australia',
    'Brazil',
    'Cambodia',
    'Cook Islands',
    'Djibouti',
    'Fiji',
    'Finland',
    'Germany',
    'Indonesia',
    'Israel',
    'Japan',
    'Jordan',
    'Kenya',
    'Kiribati',
    'Laos',
    'Luxembourg',
    'Marshall Islands',
    'Mauritius',
    'Mexico',
    'Micronesia',
    'Myanmar',
    'Nauru',
    'New Zealand',
    'Niue Island',
    'Norway',
    'Oman',
    'Palau',
    'Palestine',
    'Papua New Guinea',
    'Philippines',
    'Republic of Korea',
    'Russia',
    'Samoa',
    'Singapore',
    'Solomon Islands',
    'Sri Lanka',
    'Thailand',
    'Tonga',
    'Tuvalu',
    'UAE (United Arab Emirates)',
    'Ukraine',
    'USA (United States of America)',
    'Vanuatu',
    'Vietnam'
  ];
  
  export default countries;
  